create or replace
PACKAGE BUG_TRACKER_CRUD
IS

  FUNCTION VIEW_ALL_BUGS(
      user_id IN resources.emp_id%TYPE
      --results_tbl IN OUT BUG_TRACKER_TYPES.RESULTS_TABLE
  ) RETURN BUG_TRACKER_TYPES.RESULTS_TABLE;
  
  FUNCTION INSERT_NEW_BUG(
      user_id IN resources.emp_id%TYPE,
      v_bug_type_id bugs.bug_type_id%TYPE,
      v_project_id bugs.project_id%TYPE,
      v_description bugs.description%TYPE,
      v_priority bugs.priority%TYPE
  ) RETURN BUG_TRACKER_TYPES.RESULTS_TABLE;
  
  FUNCTION update_status_to_assigned 
(
  P_USERID IN RESOURCES.EMP_ID%TYPE,
  P_BUGID IN BUGS.BUG_ID%TYPE,
  P_ASSIGNED_USER IN RESOURCES.EMP_ID%TYPE
) RETURN BUG_TRACKER_TYPES.RESULTS_TABLE;

  FUNCTION update_status_to_testing 
(
  P_USERID IN RESOURCES.EMP_ID%TYPE,
  P_BUGID IN BUGS.BUG_ID%TYPE,
  P_ASSIGNED_USER IN RESOURCES.EMP_ID%TYPE
) RETURN BUG_TRACKER_TYPES.RESULTS_TABLE;

  FUNCTION update_status_to_resolved 
  (
    P_USERID IN RESOURCES.EMP_ID%TYPE,
    P_BUGID IN BUGS.BUG_ID%TYPE
  ) RETURN BUG_TRACKER_TYPES.RESULTS_TABLE;
  
  
  FUNCTION update_priority
  (
    P_USERID IN RESOURCES.EMP_ID%TYPE,
    P_PRIORITY IN BUGS.PRIORITY%TYPE,
    P_BUGID IN BUGS.BUG_ID%TYPE
  ) RETURN BUG_TRACKER_TYPES.RESULTS_TABLE;
  
  FUNCTION update_description
  (
    P_USERID IN RESOURCES.EMP_ID%TYPE,
    P_DESCRIPTION IN BUGS.DESCRIPTION%TYPE,
    P_BUGID IN BUGS.BUG_ID%TYPE
  ) RETURN BUG_TRACKER_TYPES.RESULTS_TABLE;
  
  FUNCTION delete_bug 
  (
    P_USERID IN RESOURCES.EMP_ID%TYPE,
    P_BUGID IN BUGS.BUG_ID%TYPE
  ) RETURN BUG_TRACKER_TYPES.RESULTS_TABLE;
  
  FUNCTION insert_bug_note
  (
    P_USERID IN RESOURCES.EMP_ID%TYPE,
    P_BUGID IN BUGS.BUG_ID%TYPE,
    P_BUG_NOTE IN BUG_NOTES.BUG_NOTE%TYPE
  ) RETURN BUG_TRACKER_TYPES.RESULTS_TABLE; 
  
  FUNCTION insert_resource_assignation
(
  P_USERID IN RESOURCES.EMP_ID%TYPE,
  P_BUGID IN BUGS.BUG_ID%TYPE,
  P_ASSIGNED_USER IN RESOURCES.EMP_ID%TYPE
) RETURN BUG_TRACKER_TYPES.RESULTS_TABLE;
  
END BUG_TRACKER_CRUD;